version: '3.9'

services:
  db:
    image: postgres
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: drac1661
      POSTGRES_PASSWORD: Drac1661@
      POSTGRES_DB: udm_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: